import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  console.log(data, "alldata");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles}>
        <div>
          {data?.results?.map((item) => {
            return (
              <div className={styles.namesss}>
                {item.url}
                {/* <Image
                  src={`https://pokeapi.co/api/v2/pokemon/1`}
                  alt="Picture of the Pokeman"
                  width={500}
                  height={500}
                /> */}

                <div className={styles.signal}>{item.name}</div>
              </div>
            );
          })}
        </div>
        {/* <div>
          {data?.results?.map((item) => {
            return item.url;
          })}
        </div> */}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon`);
  const data = await res.json();
  console.log(data, "showw");

  // Pass data to the page via props
  return { props: { data } };
}
