import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  // let input =
  //   "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png";
  // let result = input.split("/")[8];
  const url =
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png";
  const urlsplit = url.split("/");
  const id = urlsplit.length - 1;
  console.log(id, "idddddss");

  console.log(data, "alldata");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.style}>
        <div className={styles.forgrid}>
          {data?.results?.map((item) => {
            return (
              <div className={styles.card}>
                {/* {item.url} */}

                <Image
                  // src={id}
                  width={250}
                  height={250}
                  onClick={() => alert("show image")}
                />

                <div className={styles.signal}>{item.name}</div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon`);
  const data = await res.json();
  console.log(data, "showw");

  // Pass data to the page via props
  return { props: { data } };
}
